Repository BakcylProgramowania/paragon_back, pull requests merged in 2023-12, with the labels that each got.

#1 (api) add oat++ lib
  .gitignore
  CMakeLists.txt
  README.md
  src/CMakeLists.txt
  src/api/.gitkeep
  src/api/Api.cpp
  src/api/CMakeLists.txt
Labels: enhancement

#5 (api) create web server
  README.md
  src/CMakeLists.txt
  src/api/Api.cpp
  src/api/AppComponent.hpp
  src/api/CMakeLists.txt
  src/api/EnvironmentWrapper.hpp
  src/api/SwaggerComponent.hpp
  src/api/controller/MyController.cpp
  src/api/controller/MyController.hpp
  src/api/dto/DTOs.hpp
  src/main.cpp
Labels: documentation, enhancement

#6 added automatic test runs using make
  .github/workflows/c-cpp.yml
  test/CMakeLists.txt
  test/example/CMakeLists.txt
Labels: enhancement

#9 Update yml to work with database libs
  .github/workflows/c-cpp.yml
Labels: enhancement

#10 added files for docker
  Dockerfile
  appstarter.sh
Labels: enhancement

#3 (database) add mongodb libs
  README.md
  src/CMakeLists.txt
  src/database/CMakeLists.txt
  src/database/database.cpp
Labels: documentation, enhancement

#8 (core) add json lib
  CMakeLists.txt
  README.md
  src/CMakeLists.txt
  src/core/CMakeLists.txt
  src/core/core.cpp
  src/core/core.hpp
  src/main.cpp
  test/CMakeLists.txt
  test/core/CMakeLists.txt
  test/core/core_test.cpp
Labels: enhancement

#15 change #ifndef to #pragma once
  src/api/AppComponent.hpp
  src/api/EnvironmentWrapper.hpp
  src/api/SwaggerComponent.hpp
  src/api/controller/MyController.hpp
  src/api/dto/DTOs.hpp
Labels: enhancement, api
